### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by AbbasGoudarzi** [saeedvaziry/laravel-monitoring#10]
When I load monitoring route, it has a syntax error:

Message: syntax error, unexpected '=>' (T_DOUBLE_ARROW)
Exception: ParseError
Code: 0
Line: 53
Url: /monitoring/records
Referer: /monitoring
Request Method: GET
Request Inputs: {"duration":"hour"}

PHP: 7.3
Laravel: 8.78
OS: CentOs 7

maybe in this path: src/Http/MonitoringRecordController.php(line: 11)

**Comment by saeedvaziry** [comment]
@AbbasGoodarzi What php version do you use?

**Comment by saeedvaziry** [comment]
@AbbasGoodarzi It's because of the `match` function which is supported only in php 8
It will be fixed soon

**Comment by AbbasGoudarzi** [comment]
> 

Thanks

**Comment by saeedvaziry** [comment]
https://github.com/saeedvaziry/laravel-monitoring/pull/11

**Comment by saeedvaziry** [comment]
@AbbasGoodarzi Run `composer update saeedvaziry/laravel-monitoring` and you should be fine
