### ISSUE TITLE
use laravel scheduler instead of crontab tab

### ISSUE THREAD

**Issue by hairmenu** [saeedvaziry/laravel-monitoring#9]
I think adding the following in the kernel will give the same as editing the crontab.. without editing it

$schedule->command('monitoring:record')->everyMinute();
$schedule->command('monitoring:purge')->daily(); //Adjust accordingly

My 2 cents

**Comment by saeedvaziry** [comment]
@hairmenu absolutely true. In any case, you need to update the crontab though.
It's Laravel, You can use it in any way you like 😃
